### ISSUE TITLE
WindowIcon missing implementation? Or obsolete feature?

### ISSUE THREAD

**Issue by bcssov** [CreateLab/MessageBox.Avalonia#12]
Currently the specified parameter does nothing, is this feature missing implementation? If it is not, can you hide the default window icon at least?

**Comment by CreateLab** [comment]
On prev  version it's is a feature.
I'm preparing for 0.9.2 where i change all icons and allow user set his owns icon.

In previous versions used avalonia icon. As I think it is not correct and try to fix it step by step

**Comment by NoralK** [comment]
Any update on this issue, I am using 0.10.0-prev2?
