### ISSUE TITLE
Height problem

### ISSUE THREAD

**Issue by K-MeLeOn** [CreateLab/MessageBox.Avalonia#19]
Hi,

Thanks you for this project, I'm trying to use it.
But I have a problem with Height and Width.
All appear in big size as you can see in my shared picture.
I'm using version 0.9.6.1 with Rider, .NET Core , C# and Avalonia on MacOS.

The code:
`
            MessageBoxManager.GetMessageBoxStandardWindow(new MessageBoxStandardParams{
                ButtonDefinitions = ButtonEnum.Ok,
                ContentTitle = "Test tiltle",
                ContentMessage = "Test message",
                Icon = Icon.Database,
                Style = Style.MacOs
            }).Show();
`

<img width="1271" alt="Capture d’écran 2020-07-20 à 02 05 00" src="https://user-images.githubusercontent.com/47109782/87888493-798f6080-ca2d-11ea-9eb1-4ece9d065f40.png">

**Comment by CreateLab** [comment]
https://github.com/CreateLab/MessageBox.Avalonia/issues/17
https://github.com/CreateLab/MessageBox.Avalonia/issues/3

It's Avalonia problem on macOS. You will help me, if you create issue with this problem in Avalonia repo.
(Close issue if u have no more questions)

**Comment by CreateLab** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/3360
