### ISSUE TITLE
How to change the FontFamily?

### ISSUE THREAD

**Issue by rakuten** [CreateLab/MessageBox.Avalonia#2]
In the case of displaying Asian characters, will get some square characters.

If change FontFamily to "Microsoft YaHei", this problem can be solved.

But this will affect Linux users because there is no such font.

**Comment by CreateLab** [comment]
It's problem of avalonia (not message box)
as I know, u should pack font with project and use it locally
If u need ability to change font only in message box (not in all project) create new issue with this proposal, now u can change font only globally in app's styles
