### ISSUE TITLE
The possibility to change the message box window icon

### ISSUE THREAD

**Issue by IGlGI** [CreateLab/MessageBox.Avalonia#25]
Hello everyone, I've found out that it's impossible to change the message box window icon. I've tried to fix it by myself but I don't have enough permissions.
Could you check it out, please?

![image](https://user-images.githubusercontent.com/34499228/91293567-e3272b00-e7a0-11ea-87fd-3d946eb16cef.png)

**Comment by CreateLab** [comment]
yes now this feature is removed, but if u need i try to fix it back in new release

**Comment by IGlGI** [comment]
Okay, thanks. Can I get the permissions?

**Comment by CreateLab** [comment]
> 
> 
> Okay, thanks. Can I get the permissions?

You may send pull request or wait

**Comment by IGlGI** [comment]
I've tried to create a new branch and create the pull request, but I don't have permission because I'm not on the contributor's list.
