### ISSUE TITLE
About The Windows Size

### ISSUE THREAD

**Issue by rakuten** [CreateLab/MessageBox.Avalonia#3]
I always get a very large pop-up window under Mac. 

Is there any way to adjust the size of MessageBox?

Environment:
MacOS 10.14.4
Avalonia 0.9.0-preview7
MessageBox 0.9.0-preivew5

**Comment by CreateLab** [comment]
May u attach photo?

**Comment by rakuten** [comment]
This is my code. The size of the pop-up window is larger than 1024 * 768, and it is not centered

And I found other problems

Setting "messageboxparam. Window" will cause no window to pop up, and setting icon = icon.setting will be the same (but it can be set to something else)

```shell
try
{
    var messageBoxParam = new MessageBoxStandardParams
    {
        ButtonDefinitions = ButtonEnum.Ok,
        ContentTitle = "test",
        ContentMessage = "testtest!",
        Icon = Icon.None,
        Style = Style.UbuntuLinux
    };
    //messageBoxParam.Window.Width = 300;
    //messageBoxParam.Window.Height = 150;
    //messageBoxParam.Window.WindowStartupLocation = WindowStartupLocation.CenterOwner;
    var window = MessageBoxManager.GetMessageBoxStandardWindow(messageBoxParam);
    window.ShowDialog(this.VisualRoot as Window);
}
catch (Exception e)
{
    Console.WriteLine(e.Message);
}
```

**Comment by rakuten** [comment]
The window didn't pop up and it didn't throw an Exception. It just didn't happen.

And...

Calling "ShowDialog()" is also invalid. When a pop-up window is popped up, a separate window will pop up instead of inside mainWindow.

**Comment by CreateLab** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/3360
fix is 
 var msgParams = new MessageBoxStandardParams
            {
                CanResize = true,
                ContentTitle = "Title",
                ContentMessage = "message"
            };
            await MessageBoxManager.GetMessageBoxStandardWindow(msgParams).Show();
