### ISSUE TITLE
Code review/feedback

### ISSUE THREAD

**Issue by ForNeVeR** [CreateLab/MessageBox.Avalonia#5]
Hello! As you requested, I've performed a complete review of your project. I have the following points to say:

1. Better use `<PackageLicenseExpression>MIT</PackageLicenseExpression>` instead of https://github.com/CreateLab/MessageBox.Avalonia/blob/881395a830e3cecb035d891a21cb4ec5ff3e75f1/MessageBox.Avalonia/MessageBox.Avalonia.csproj#L10
   `PackageLicenseUrl` is deprecated.
2. I can't see any point in defining `AbstractBaseWindow`: it isn't used anywhere in the project. Should you just drop this class?
3. I don't like the [the `BaseWindows`](https://github.com/CreateLab/MessageBox.Avalonia/tree/881395a830e3cecb035d891a21cb4ec5ff3e75f1/MessageBox.Avalonia/BaseWindows) at all:
   - they're named the same as the corresponding views, but at the same time, they aren't the views but just wrappers
   - they aren't `BaseWindows` either:
     - they aren't "base" in any sense (well, _maybe_ the `AbstractBaseWindow` may be considered "base", but others definitely don't)
     - they aren't windows; just simple wrapper classes
   - their code is identical

   I suggest you drop these "base windows" and
   - add an interface for your windows that will only contain async variants of `Show`/`ShowDialog`
   - implement the interface explicitly in your window classes (or maybe in a base class)
   - return this interface from your `MessageBoxManager` methods

   **Pros:**
   - no strange business with `BaseWindows`
   - no code duplication between two classes
   - lesser memory traffic (because no boxing allocations)
4. `Extentions` → `Extensions`
5. Honestly I'm not sure if your `SetStyleExtension` should be `public`. I believe you better make it `internal`, because it has no use outside of your library. Right? No user needs their code to be polluted by your innocently-looking `SetStyle` extension method.
6. Most `private set;` statements in your view models may easily be deleted. C# 6 (I think) already supports read-only properties without `private set`.
7. `ViewModelBase` is completely redundant (not all of your view models even inherit from it!)
8. Are you sure it's okay that `MsBoxStandardViewModel` doesn't inherit `ReactiveObject`?
9. I believe that `HasIcon`/`ImagePath` duplication is redundant. `HasIcon` can be made a calculated property (calculated from `ImagePath != null`) or just dropped (I can't see any usages of it).
10. `@params.Icon.ToString().ToLower()` — it is **never** safe to write code like that. It won't pass [the Turkey test](https://stackoverflow.com/questions/796986/what-is-the-turkey-test). Always specify the invariant culture explicitly, or use `ToLowerInvariant()`
11. From the code, it looks like `MessageBoxCustomParams.Window`/`MessageBoxStandardParams.Window` property isn't for user code (and thus shouldn't be public), and you use it only to pass a window from the `MessageBoxManager` to your view models. I believe you could eliminate this field from the `Params` classes, and simply pass an additional parameter to the view model constructors.

    Or you may even remove the `*ViewModel._window` completely if you add a `ButtonClicked` event to your view models, and subscribe to the event outside of the view model code. [People say](https://stackoverflow.com/q/4376475/2684760) that this kind of decoupling of the view model from the view is generally a good idea.
12. `MsBoxCustomViewModel` and `MsBoxStandardViewModel` have a good share of common/copy-pasted code. Are you sure you can't share the code somehow? E.g. via inheritance, base class extraction of something like that?
13. I can't see how `MsBoxCustomViewModel` uses its inheritance from `ViewModelBase`. Are you sure `ViewModelBase` is necessary? I think it's possible to drop this inheritance and get rid of the whole `Avalonia.ReactiveUI` dependency, which is very good (since it is unused, at least).
14. I have my doubts about `Icon.Avalonia`: first of all, it is a default icon, and second: its quality is extremely crappy.

    I believe that it could only be used for demonstration purposes and shouldn't really be used in production. Could you simply remove it?

**Comment by CreateLab** [comment]
1 2 3 4 5 7 8 9  10  12  13 14
