### ISSUE TITLE
Show MessageBox in Center of Parent

### ISSUE THREAD

**Issue by josegomez** [CreateLab/MessageBox.Avalonia#7]
Right now the message box appears either in the Center of the Screen, or just somewhere (random seeming)
It would be good if we could pass the parent (window) and have it show in the center of that window.

**Comment by CreateLab** [comment]
preparing to end code feedback issue 5
next will start new enhancement

**Comment by josegomez** [comment]
@CreateLab, Would you accept a PR on this?

**Comment by josegomez** [comment]
Sent a PR on it, I really needed this in my project,so even if it isn't merged I still need to have it in my own project thank you! 
Hope it helps

**Comment by CreateLab** [comment]
> Sent a PR on it, I really needed this in my project,so even if it isn't merged I still need to have it in my own project thank you!
> Hope it helps
Yep
Test only in Kubuntu Linux, works bad, but it's avalonia problem
https://www.nuget.org/packages/MessageBox.Avalonia/0.9.0.1-prev

**Comment by CreateLab** [comment]
May I close issue?

**Comment by josegomez** [comment]
Yes thank you!

**Comment by CreateLab** [comment]
> Yes thank you!

if u share ur project with me
i can pin it in readme
and will be grateful

**Comment by josegomez** [comment]
Sure my project is 
https://github.com/sqrldev/SQRLDotNetClient
